// <auto-generated />
namespace RentalOffice.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class address_userMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(address_userMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201508111214429_address_userMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
